<a href="https://colab.research.google.com/github/adityajangid10/datascience/blob/main/machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.diag([1,45,78,90])
a

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [3]:
# (5)random module

In [4]:
#(5a)randint()------------> random + integer
# it will create an array in which it will provide ramndom numbers
# in a given range .

In [5]:
# syntax: np.random.randint(min_number,max_number,total)

In [6]:
a= np.random.randint(1,10,3)
a

array([7, 3, 6])

In [7]:
# (5b).seed()---> it will fix your random generated data.

In [8]:
np.random.seed(78)
a=np.random.randint(1,10,3)
a

array([6, 7, 8])

In [9]:
# (5c). rand()---->it will generate numbers in range 0-1.


In [10]:
a = np.random.rand(5)
a

array([0.5733576 , 0.59658201, 0.32560075, 0.76062093, 0.99367239])

In [11]:
# (6). linespace(min,max,total_number)------->
# it will create an array in which it will provide same step number
# value in a given range.

In [12]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [13]:
  # 11-50 mid 4 random generate
  # array ---->   [7,7,7,7,7,7,7,7]
  # 2-d [11-19] array -----> shape ,size ,dimension

In [14]:
# 11-50 mid 4 random generate
a= np.linspace(11,50,4)
a

array([11., 24., 37., 50.])

In [15]:
# 11-50 mid 4 random generate
a=np.random.randint(11,50,4)
a

array([23, 15, 31, 33])

In [16]:
# array ---->   [7,7,7,7,7,7,7,7]
a=np.array([7,7,7,7,7,7,7,7])
a

array([7, 7, 7, 7, 7, 7, 7, 7])

In [17]:
# 2-d [11-19] array -----> shape ,size ,dimension


In [18]:
# reshaping the array
# n(rows)* n(columns)= n(total_elements)

In [19]:
a= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
# 1*12, 12*1
# 2*6, 6*2
# 3*4, 4*3


In [21]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
a.reshape(6,5)

ValueError: cannot reshape array of size 12 into shape (6,5)

In [24]:
#-------------------------------------- date 09-10-2026----------------------------

In [25]:
import numpy as np

In [26]:
# view vs copy
# view means modification in original data while copy means
# change in dupicates data will not reflect original data.

In [27]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [28]:
b = a[3:6]
b[:] = 0

In [29]:

a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [30]:
a = np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
b = a[3:6].copy()
b[:] = 0

In [32]:



a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [33]:
# np.arange(min_number,max_number,step_number)--------->

In [34]:
a = np.arange(1,10,3)
a

array([1, 4, 7])

In [35]:
a = np.arange(1,51,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [36]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [37]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [38]:
a+b ## 1+5=6 , 2+6=8, 3+7=10 , 4+8=12

array([[ 6,  8],
       [10, 12]])

In [39]:
a-b

array([[-4, -4],
       [-4, -4]])

In [40]:
a.dot(b) ### for matrix multiplication

array([[19, 22],
       [43, 50]])

In [41]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [42]:
a**3

array([[ 1,  8],
       [27, 64]])

In [43]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
print("total sum of a matrix:",np.sum(a))
print("row wise sum:", np.sum(a,axis=1))
print("column wise sum:", np.sum(a,axis=0))

total sum of a matrix: 45
row wise sum: [ 6 15 24]
column wise sum: [12 15 18]


In [45]:
# unique()-------> it will remove duplicate elements from an array.
# a -------> unique element array
# return_index=True ----> return indexing of unique elements
# return_counts=True ----> total frequency of each unique items

In [46]:
a = np.array([1,2,3,1,1,1,2,4,4,4,4,4,4])
a

array([1, 2, 3, 1, 1, 1, 2, 4, 4, 4, 4, 4, 4])

In [47]:
np.unique(a,return_index=True , return_counts=True)

(array([1, 2, 3, 4]), array([0, 1, 2, 7]), array([4, 2, 1, 6]))

In [48]:
# horizontal and vertical sacling
# horizontal sacling means combined 2 or more array in horizontally
# and vertical scaling means combined 2 or more arrray in vertically.


In [49]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [50]:
b = np.arange(5,9)
c= np.arange(9,13)

In [51]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
# matrix (11-50),elements -----> martrix 4*4-----> rw wise sum ,column wise ,total sum
# matrix (11-20), matrix(31-40)----->reshape(2*5)-----> a+b.

In [54]:
# matrix (11-50),elements -----> martrix 4*4-----> rw wise sum ,column wise ,total sum

a = np.random.randint(11, 50, 16).reshape(4, 4)

#print("Matrix:,a")
print(a)

print("Row-wise sum:")
print(np.sum(a, axis=1))

print("Column-wise sum:")
print(np.sum(a, axis=0))

print("Total sum:")
print(np.sum(a))

[[49 43 14 49]
 [15 36 34 41]
 [13 39 24 34]
 [41 46 48 39]]
Row-wise sum:
[155 126 110 174]
Column-wise sum:
[118 164 120 163]
Total sum:
565


In [55]:
# matrix (11-20), matrix(31-40)----->reshape(2*5)-----> a+b.
import numpy as np

a = np.arange(11, 21).reshape(2, 5)
b = np.arange(31, 41).reshape(2, 5)

print("Matrix A:")
print(a)

print("Matrix B:")
print(b)

print("A + B:")
print(a + b)

Matrix A:
[[11 12 13 14 15]
 [16 17 18 19 20]]
Matrix B:
[[31 32 33 34 35]
 [36 37 38 39 40]]
A + B:
[[42 44 46 48 50]
 [52 54 56 58 60]]
